from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class AssetSpec:
    key: str
    code: str
    fa_name: str
    en_name: str
    category: str
    unit_fa: str
    emoji: str
    aliases: tuple[str, ...]
    lookup_terms: tuple[str, ...]


ASSETS: tuple[AssetSpec, ...] = (
    AssetSpec(
        "usd",
        "USD",
        "دلار آمریکا",
        "US Dollar",
        "currency",
        "دلار",
        "💵",
        ("دلار آمریکا", "دلار امریکا", "دلار", "usd", "us dollar", "dollar"),
        ("usd", "us dollar", "دلار آمریکا", "دلار"),
    ),
    AssetSpec(
        "eur",
        "EUR",
        "یورو",
        "Euro",
        "currency",
        "یورو",
        "💶",
        ("یورو", "eur", "euro"),
        ("eur", "euro", "یورو"),
    ),
    AssetSpec(
        "gbp",
        "GBP",
        "پوند انگلیس",
        "British Pound",
        "currency",
        "پوند",
        "💷",
        ("پوند انگلیس", "پوند", "gbp", "british pound", "pound"),
        ("gbp", "british pound", "پوند"),
    ),
    AssetSpec(
        "aed",
        "AED",
        "درهم امارات",
        "UAE Dirham",
        "currency",
        "درهم",
        "🇦🇪",
        ("درهم امارات", "درهم", "aed", "uae dirham", "dirham"),
        ("aed", "uae dirham", "درهم"),
    ),
    AssetSpec(
        "try",
        "TRY",
        "لیر ترکیه",
        "Turkish Lira",
        "currency",
        "لیر",
        "🇹🇷",
        ("لیر ترکیه", "لیر", "try", "turkish lira", "lira"),
        ("try", "turkish lira", "لیر"),
    ),
    AssetSpec(
        "cad",
        "CAD",
        "دلار کانادا",
        "Canadian Dollar",
        "currency",
        "دلار کانادا",
        "🇨🇦",
        ("دلار کانادا", "cad", "canadian dollar"),
        ("cad", "canadian dollar", "دلار کانادا"),
    ),
    AssetSpec(
        "aud",
        "AUD",
        "دلار استرالیا",
        "Australian Dollar",
        "currency",
        "دلار استرالیا",
        "🇦🇺",
        ("دلار استرالیا", "aud", "australian dollar"),
        ("aud", "australian dollar", "دلار استرالیا"),
    ),
    AssetSpec(
        "chf",
        "CHF",
        "فرانک سوئیس",
        "Swiss Franc",
        "currency",
        "فرانک",
        "🇨🇭",
        ("فرانک سوئیس", "فرانک", "chf", "swiss franc", "franc"),
        ("chf", "swiss franc", "فرانک"),
    ),
    AssetSpec(
        "cny",
        "CNY",
        "یوان چین",
        "Chinese Yuan",
        "currency",
        "یوان",
        "🇨🇳",
        ("یوان چین", "یوان", "cny", "chinese yuan", "yuan"),
        ("cny", "chinese yuan", "یوان"),
    ),
    AssetSpec(
        "rub",
        "RUB",
        "روبل روسیه",
        "Russian Ruble",
        "currency",
        "روبل",
        "🇷🇺",
        ("روبل روسیه", "روبل", "rub", "russian ruble", "ruble"),
        ("rub", "russian ruble", "روبل"),
    ),
    AssetSpec(
        "iqd",
        "IQD",
        "دینار عراق",
        "Iraqi Dinar",
        "currency",
        "دینار",
        "🇮🇶",
        ("دینار عراق", "دینار", "iqd", "iraqi dinar"),
        ("iqd", "iraqi dinar", "دینار عراق"),
    ),
    AssetSpec(
        "sar",
        "SAR",
        "ریال عربستان",
        "Saudi Riyal",
        "currency",
        "ریال عربستان",
        "🇸🇦",
        ("ریال عربستان", "sar", "saudi riyal"),
        ("sar", "saudi riyal", "ریال عربستان"),
    ),
    AssetSpec(
        "jpy",
        "JPY",
        "ین ژاپن",
        "Japanese Yen",
        "currency",
        "ین",
        "🇯🇵",
        ("ین ژاپن", "ین", "jpy", "japanese yen", "yen"),
        ("jpy", "japanese yen", "ین"),
    ),
    AssetSpec(
        "gold18",
        "GOLD18",
        "طلای ۱۸ عیار",
        "18K Gold",
        "gold",
        "گرم",
        "🥇",
        (
            "طلای ۱۸ عیار",
            "طلای 18 عیار",
            "طلا ۱۸",
            "طلا 18",
            "۱۸ عیار",
            "18 عیار",
            "طلا",
            "gold 18k",
            "18k gold",
            "gold",
        ),
        (
            "gold18",
            "gold_18",
            "gold 18",
            "18k",
            "18 karat",
            "gram18",
            "geram18",
            "18 عیار",
            "طلای 18",
            "طلای ۱۸",
        ),
    ),
    AssetSpec(
        "gold24",
        "GOLD24",
        "طلای ۲۴ عیار",
        "24K Gold",
        "gold",
        "گرم",
        "🥇",
        (
            "طلای ۲۴ عیار",
            "طلای 24 عیار",
            "طلا ۲۴",
            "طلا 24",
            "۲۴ عیار",
            "24 عیار",
            "gold 24k",
            "24k gold",
        ),
        (
            "gold24",
            "gold_24",
            "gold 24",
            "24k",
            "24 karat",
            "gram24",
            "geram24",
            "24 عیار",
            "طلای 24",
            "طلای ۲۴",
        ),
    ),
    AssetSpec(
        "mesghal",
        "MESGHAL",
        "مثقال طلا",
        "Gold Mesghal",
        "gold",
        "مثقال",
        "⚖️",
        ("مثقال طلا", "مثقال", "mesghal", "mithqal"),
        ("mesghal", "mithqal", "مثقال"),
    ),
    AssetSpec(
        "ounce",
        "OUNCE",
        "اونس جهانی طلا",
        "Gold Ounce",
        "gold",
        "اونس",
        "🌍",
        ("اونس جهانی طلا", "اونس جهانی", "اونس طلا", "اونس", "gold ounce", "ounce", "xau"),
        ("ounce", "gold ounce", "xau", "اونس"),
    ),
    AssetSpec(
        "emami",
        "EMAMI",
        "سکه امامی",
        "Emami Coin",
        "coin",
        "سکه",
        "🪙",
        ("سکه امامی", "امامی", "emami coin", "emami"),
        ("emami", "imam", "سکه امامی"),
    ),
    AssetSpec(
        "bahar",
        "BAHAR",
        "سکه بهار آزادی",
        "Bahar Azadi Coin",
        "coin",
        "سکه",
        "🪙",
        ("سکه بهار آزادی", "بهار آزادی", "bahar azadi", "bahar"),
        ("bahar", "azadi", "بهار آزادی"),
    ),
    AssetSpec(
        "halfcoin",
        "HALF_COIN",
        "نیم سکه",
        "Half Coin",
        "coin",
        "سکه",
        "🪙",
        ("نیم سکه", "نیم‌سکه", "half coin"),
        ("half coin", "halfcoin", "nim", "نیم سکه"),
    ),
    AssetSpec(
        "quartercoin",
        "QUARTER_COIN",
        "ربع سکه",
        "Quarter Coin",
        "coin",
        "سکه",
        "🪙",
        ("ربع سکه", "ربع‌سکه", "quarter coin"),
        ("quarter coin", "quartercoin", "rob", "ربع سکه"),
    ),
    AssetSpec(
        "gramcoin",
        "GERAMI_COIN",
        "سکه گرمی",
        "Gerami Coin",
        "coin",
        "سکه",
        "🪙",
        ("سکه گرمی", "گرمی", "gerami coin", "gram coin"),
        ("gerami", "gram coin", "سکه گرمی"),
    ),
)


ASSET_BY_KEY = {asset.key: asset for asset in ASSETS}
